version: '2.1'

services:
  web:
    env_file: .env.development
    build: 
      args:
        - NODE_ENV=development
      context: .
    image: 'brunoluiz/pru-warehouse'
    volumes:
      - .:/opt/pru-warehouse
    ports:
      - '8080:80'
    links:
      - 'postgres:db.host'
    depends_on:
      postgres:
        condition: service_healthy
    command: ./node_modules/.bin/nodemon ./app.js --inspect=0.0.0.0:9229

  postgres:
    image: 'postgres:alpine'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 10s
      retries: 10